# Generated by Django 2.2.8 on 2019-12-13 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=20, verbose_name='イベント名')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('application_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='募集開始日時')),
                ('application_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='募集締切日時')),
                ('place', models.CharField(max_length=50, verbose_name='場所')),
                ('meeting_place', models.CharField(max_length=50, verbose_name='集合場所')),
                ('details', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('admin_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主催チーム')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('people_num', models.PositiveIntegerField(verbose_name='申し込み人数')),
                ('remarks', models.TextField(verbose_name='備考')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Event', verbose_name='イベント')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='チーム')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
